ALTER TABLE medication 
ADD COLUMN IF NOT EXISTS reminder_type VARCHAR(20) DEFAULT 'NOTIFICATION',
ADD COLUMN IF NOT EXISTS lead_time_minutes INT DEFAULT 5,
ADD COLUMN IF NOT EXISTS snooze_interval_minutes INT DEFAULT 10;